// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4CJwm7FzYJ8p7IbrBMw8B7jJ60Uvu0aI',
    appId: '1:300994975951:web:d4fc7ce4894a770dd33fba',
    messagingSenderId: '300994975951',
    projectId: 'academy-ebelajar',
    authDomain: 'academy-ebelajar.firebaseapp.com',
    storageBucket: 'academy-ebelajar.appspot.com',
    measurementId: 'G-RRD1WTE357',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtkmncaKUm_EurX7AQ7ROj19rYxlhfI0E',
    appId: '1:300994975951:android:bb000d09c6e4eab2d33fba',
    messagingSenderId: '300994975951',
    projectId: 'academy-ebelajar',
    storageBucket: 'academy-ebelajar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4lSjTxeQOD_WGqPArJHbg02FypShBK2g',
    appId: '1:300994975951:ios:50bb7480efd1bcd8d33fba',
    messagingSenderId: '300994975951',
    projectId: 'academy-ebelajar',
    storageBucket: 'academy-ebelajar.appspot.com',
    iosClientId: '300994975951-ruhv5empbldo5g5f83uvovukf5ngib8i.apps.googleusercontent.com',
    iosBundleId: 'com.capstone11.lmsApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4lSjTxeQOD_WGqPArJHbg02FypShBK2g',
    appId: '1:300994975951:ios:50bb7480efd1bcd8d33fba',
    messagingSenderId: '300994975951',
    projectId: 'academy-ebelajar',
    storageBucket: 'academy-ebelajar.appspot.com',
    iosClientId: '300994975951-ruhv5empbldo5g5f83uvovukf5ngib8i.apps.googleusercontent.com',
    iosBundleId: 'com.capstone11.lmsApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4CJwm7FzYJ8p7IbrBMw8B7jJ60Uvu0aI',
    appId: '1:300994975951:web:2c3a550fcdc36271d33fba',
    messagingSenderId: '300994975951',
    projectId: 'academy-ebelajar',
    authDomain: 'academy-ebelajar.firebaseapp.com',
    storageBucket: 'academy-ebelajar.appspot.com',
    measurementId: 'G-JZSRV44K48',
  );
}
